import { TDocumentDefinitions } from 'pdfmake/interfaces';

interface ReportOptions {
  title: string;
}

export const getHelloWorldDocDefinition = (
  options: ReportOptions,
): TDocumentDefinitions => {
  return {
    content: [
      { text: options.title || 'Hello World', style: ['header', 'boldTitle'] },
      { text: 'This is a simple PDF document generated by NestJS.' },
      { text: 'Enjoy creating PDFs with pdfmake!' },
    ],
    styles: {
      boldTitle: {
        bold: true,
        fontSize: 18,
        margin: [0, 0, 0, 10],
      },
    },
  };
};
